[[docs]]
  name = "起步"
  weight = 10
  identifier = "prologue"
  url = "/docs/prologue/"

[[docs]]
  name = "手册"
  weight = 20
  identifier = "manual"
  url = "/docs/manual/"

[[docs]]
  name = "高级应用"
  weight = 30
  identifier = "advanced-application"
  url = "/docs/advanced-application/"

[[docs]]
  name = "帮助"
  weight = 60
  identifier = "help"
  url = "/docs/help/"

[[main]]
  name = "文章精选"
  url = "/docs/prologue/article/"
  weight = 10

[[main]]
  name = "关于我们"
  url = "/docs/prologue/about/"
  weight = 20

